#Assignment
#Variable Year + Input Function
while #year != 0:
    #if code comes in here with the subtraction
    #print the person's age
    #else print wrong value inserted
    break

def AgeCalculator():
    from datetime import date
    Age=int(input("Please enter your month and year of birth"))
    months=current_date.month - birth_date.month
    years=current_date.year - birth_date.year
    birth_month = int(input("Enter your birth month: "))
    birth_year = int(input("Enter your birth year: "))

    if months < 0:
       years -= 1
       months += 2
    else :
     print ("Invalid birth month and year entered")
     ("Thank you for participating")
     
AgeCalculator()