#Tuples
Tupledemo=(2004202301,"Stanoc Baim",23,"CCDM")
print(Tupledemo)
print(type(Tupledemo))

#Dictionary
#Create a Dictionary and call this Staff
#It should contain the details
#ID:1102,Name:Shirley Komogi, Role:IT Trainee, Phone:3267424
Staff={"ID":1102,"Name":"Shirley Komogi","Role":"IT Trainee","Phone":3267424}
print(Staff)
print(Staff["Role"])

#Exercise
#Q1: Create an Object to hold this data, call it CEIT Courses.
CEITCourse={1001:"CCLSA",1002:"CCIT",1003:"CCDM",1004:"CCNS"}
print(CEITCourse)

#Q2:
UPNGSchools={["SOL",120],["SHSS",90],["SMHS",150],["SNPS",100],["SBPP",200]}
print(UPNGSchools)

#Q3:
StaffJT=[223, "Name":"John Tambu", "Role":"Payroll Officer"]
StaffJM=[332, "Name":"Jimmy Masin", "Role":"Auditor"]

